services:
  # -----------------------------------------------------------
  # CONTENEDOR 1: LA BASE DE DATOS MYSQL
  # -----------------------------------------------------------
  db-servicio:
    image: mysql:8.0
    container_name: mysql_servidor
    environment:
      MYSQL_ROOT_PASSWORD: clave_maestra_root
      MYSQL_DATABASE: universidad_backend
      MYSQL_USER: desarrollador
      MYSQL_PASSWORD: password_seguro_123
    ports:
      - "3306:3306"
    networks:
      - red_interna_proyecto
    volumes:
      - persistencia_db:/var/lib/mysql

  # -----------------------------------------------------------
  # CONTENEDOR 2: EL ENTORNO DE TRABAJO JAVA/SPRING BOOT
  # -----------------------------------------------------------
  workspace-java:
    image: maven:3.9-eclipse-temurin-21
    container_name: entorno_programacion
    ports:
      - "8080:8080"
    depends_on:
      - db-servicio
    networks:
      - red_interna_proyecto
    # El comando 'tail -f /dev/null' es un truco técnico.
    # Obliga al contenedor a quedarse encendido de forma permanente 
    # en estado de espera, para que podamos entrar a él a programar.
    command: tail -f /dev/null
    # Vinculamos la carpeta vacía local con la ruta '/app' del contenedor.
    volumes:
      - ./codigo-fuente:/app
    # Por defecto, el contenedor iniciará en la carpeta /app
    working_dir: /app

networks:
  red_interna_proyecto:

volumes:
  persistencia_db: